authentication/urls.py
from django.urls import path
from authentication.views import register, login, logout_user, profile_delete, profile_detail, profile_edit

app_name = 'authentication'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout_user, name='logout_user'),
    path('profiles/<str:username>/', profile_detail, name='profile_detail'),
    path('profiles/<str:username>/edit/', profile_edit, name='profile_edit'),
    path('profiles/<str:username>/delete/', profile_delete, name='profile_delete'),
]

frontend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('manage/', include('subscription_box.urls')),
    path('subscription/', include('subscription_management.urls')), 
    path('auth/', include('authentication.urls')),
    path('reviews/', include('subsbox_review.urls'))
]

subsbox_review/urls.py
from django.urls import include, path
from subsbox_review.views import get_all_reviews, create_review, delete_review

app_name = 'subsbox_review'

urlpatterns = [
    path('', get_all_reviews, name='review_list'),
    path('create_review/', create_review, name='create_review'),
    path('reviews/delete/<str:review_id>/', delete_review, name='delete_review'),
]

subscription_box/subscription_box/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    
]

subscription_box/urls.py
from django.urls import path
from .views import *

app_name = 'subscription_box'

urlpatterns = [
    path('', manager, name='manager'),
    path('box/create', create_subscription, name='create_subscription'),
    path('box/update/<int:id>', update_subscription, name='update_subscription'),
    path('box/delete/<int:id>', delete_subscription, name='delete_subscription'),
    path('item/create', create_item, name='create_item'),
    path('item/update/<int:id>', update_item, name='update_item'),
    path('item/delete/<int:id>', delete_item, name='delete_item'),
    path('box/get/<int:id>', view_subscriptions , name='get_subscription'),
    path('item/get/<int:id>', view_items, name='get_item'),
    path('box/get', get_subscription_ajax, name='all_subscriptions'),
    path('item/get', get_item_ajax, name='all_items'),
    path('box/<int:id>', get_subscription_ajax, name='get_subscription_ajax'),
    path('item/<int:id>', get_item_ajax, name='get_item_ajax'),
]

subscription_management/urls.py
from django.urls import include, path
from . import views

app_name = 'subscription_management'

urlpatterns = [
    path('', views.box_list, name='box_list'),
    path('<int:box_id>/', views.box_detail, name='box_detail'),
    path('history/', views.subscription_history, name='subscription_history'),
    path('subscribe/<int:box_id>/', views.subscribe, name='subscribe'),
    path('cancel/<int:sub_id>/', views.cancel, name='cancel'),

    path('admins/', views.admin_list, name='admin_list'),
    path('admins/cancel/<int:sub_id>/', views.admin_cancel, name='admin_cancel'),
    path('admins/pending/<int:sub_id>/', views.admin_pending, name='admin_pending'),
    path('admins/approve/<int:sub_id>/', views.admin_approve, name='admin_approve'),

    path('fetch_boxes/', views.fetch_boxes, name='fetch_boxes'),
    path('fetch_subscriptions/', views.fetch_subscriptions, name='fetch_subscriptions'),
    path('get_all_subscriptions/', views.get_all_subscriptions, name='get_all_subscriptions')

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    
    {% block meta %}
    {% endblock meta %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">

            {% if request.COOKIES.username %}
                <a class="navbar-brand text-white font-monospace">Welcome, {{request.COOKIES.username}}!</a>
                <div style="display: flex;">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle btn btn-primary" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="font-size:13px;">
                                    Menu
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                                    <li><a class="dropdown-item" href="{% url 'subscription_management:box_list'%}">Subscription</a></li>
                                    <li><a class="dropdown-item" href="{% url 'subscription_box:manager'%}">Subscription Box</a></li>
                                    <li><a class="dropdown-item" href="{% url 'subsbox_review:review_list'%}">Review</a></li>
                                    <li><a class="dropdown-item" href="{% url 'authentication:profile_detail' request.COOKIES.username %}">My Profile</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <a href="{% url 'authentication:logout_user'%}" style="text-decoration: none;">
                        <button type="button" class="btn btn-primary">Logout</button>
                    </a>
                </div>
            {% endif %}

            {% if not request.COOKIES.username %}
                <a class="navbar-brand text-white font-monospace">Welcome, Guest!</a>
    
            {% endif %}
        </div>
    </nav>
    {% block content %}
    {% endblock content %}
</body>

</html>