frontend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('manage/', include('subscription_box.urls')),
    path('subscription/', include('subscription_management.urls')), 
    path('auth/', include('authentication.urls')),
    path('reviews/', include('subsbox_review.urls'))
]

subscription_box/subscription_box/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    
]

subscription_box/urls.py
from django.urls import path
from .views import *

app_name = 'subscription_box'

urlpatterns = [
    path('', manager, name='manager'),
    path('box/create', create_subscription, name='create_subscription'),
    path('box/update/<int:id>', update_subscription, name='update_subscription'),
    path('box/delete/<int:id>', delete_subscription, name='delete_subscription'),
    path('item/create', create_item, name='create_item'),
    path('item/update/<int:id>', update_item, name='update_item'),
    path('item/delete/<int:id>', delete_item, name='delete_item'),
    path('box/get/<int:id>', view_subscriptions , name='get_subscription'),
    path('item/get/<int:id>', view_items, name='get_item'),
    path('box/get', get_subscription_ajax, name='all_subscriptions'),
    path('item/get', get_item_ajax, name='all_items'),
    path('box/<int:id>', get_subscription_ajax, name='get_subscription_ajax'),
    path('item/<int:id>', get_item_ajax, name='get_item_ajax'),
]

subscription_box/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
import requests
from django.core import serializers
import django.contrib.messages as message
# Create your views here.

URL = 'http://35.240.230.131'

def manager(request):
    if is_admin(request):
        response = requests.get('http://35.240.230.131/subscription-box/getAll')
        print(response)
        box = response.json()
        print(box)
        
        response = requests.get('http://35.240.230.131/item/getAll')
        print(response)
        item = response.json()
        context = {
            'boxes': box,
            'items' : item
        }
        return render(request, 'manager.html', context)
    return redirect('homepage:show_homepage')


def create_subscription(request):
    if is_admin(request):
        if request.method == 'POST':
            name = request.POST.get('name')
            type = request.POST.get('type')
            price = request.POST.get('price')

            data = {
                    'name': name,
                    'type': type, 
                    'price': price
                    }
            
            response = requests.post(URL+'/subscription-box/create', json=data, headers={'Content-Type': 'application/json'})
            print(response)
            res = response.json()
            print(res)
            return HttpResponse(redirect('subscription_box:manager'), status=200)
        else:
            message.info(request, 'Invalid request method')
            return HttpResponse(status=405)
    return redirect('homepage:show_homepage')
    
def update_subscription(request,id):
    print('masuk sini')
    if is_admin(request):
        if request.method == 'POST':
            name = request.POST.get('name')
            type = request.POST.get('type')
            price = request.POST.get('price')

            data = {
                    'name': name,
                    'type': type, 
                    'price': price
                    }
            
            
            response = requests.put(URL+"/subscription-box/update/"+str(id), json=data, headers={'Content-Type': 'application/json'})
            print(response)
            return HttpResponse(status=200)
        
        else:
            message.info(request, 'Invalid request method')
            return HttpResponse(status=405)
    return redirect('homepage:show_homepage')
    
def delete_subscription(request,id):
    if is_admin(request):
        if request.method == 'POST':
            
            response = requests.delete(URL+"/subscription-box/delete/"+str(id))
            res = response.json()
            return HttpResponse(content=res,status=200)
        
        else:
            message.info(request, 'Invalid request method')
            return HttpResponse(status=405)
    return redirect('homepage:show_homepage')
    
def create_item(request):
    print('masuk sini item')
    if is_admin(request):
        if request.method == 'POST':
            name = request.POST.get('name')
            quantity = request.POST.get('quantity')

            data = {
                    'name': name,
                    'quantity': quantity,
                    }
            
            response = requests.post(URL+"/item/create", json=data, headers={'Content-Type': 'application/json'})
            print(response)
            res = response.json()
            print(res)
            return HttpResponse(redirect('subscription_box:manager'), status=200)
        
        else:
            message.info(request, 'Invalid request method')
            return HttpResponse(status=405)
    return redirect('homepage:show_homepage')
    
def update_item(request,id):
    if is_admin(request):
        if request.method == 'POST':
                name = request.POST.get('name')
                quantity = request.POST.get('quantity')

                print(name)
                print(quantity)

                data = {
                    'name': name,
                    'quantity': quantity
                    }
                
                
                response = requests.put(URL+"/item/edit/"+str(id), json=data, headers={'Content-Type': 'application/json'})
                print(response)
                return HttpResponse(redirect('subscription_box:get_item', id), status=200)
        
        else:
            message.info(request, 'Invalid request method')
            return HttpResponse(status=405)
    return redirect('homepage:show_homepage')
    
def delete_item(request,id):
    if is_admin(request):
        if request.method == 'POST':
            
            response = requests.delete(URL+"/item/delete/"+str(id))
            res = response.json()
            return HttpResponse(content=res,status=200)
        
        else:
            message.info(request, 'Invalid request method')
            return HttpResponse(status=405)
    return redirect('homepage:show_homepage')
    
def view_subscriptions(request, id):
    response = requests.get(URL+"/subscription-box/viewDetails/"+str(id))
    box = response.json()
    print(box)
    
    context = {
        "id": id,
        'box': box,
        'items' : box['items']
    }
    return render(request, 'box_detail.html', context)

def view_items(request,id):
    response = requests.get(URL+"/item/get/"+str(id))
    item = response.json()
    context = {
        "id": id,
        'item' : item
    }
    return render(request, 'item_detail.html', context)

def get_subscription_ajax(request):
    response = requests.get(URL+"/subscription-box/getAll")
    box = response.json()
    return HttpResponse(content=box, status=200)

def get_item_ajax(request):
    response = requests.get(URL+"/item/getAll")
    item = response.json()
    return HttpResponse(content=item, status=200)

def get_subscription_id_ajax(request, id):
    response = requests.get(URL+"/subscription-box/viewDetails/"+str(id))
    box = response.json()
    print(box)
    return HttpResponse(content=box, status=200)

def get_item_id_ajax(request, id):
    response = requests.get(URL+"/item/get/"+str(id))
    item = response.json()
    return HttpResponse(content=item, status=200)

def is_admin(request):
    role = request.COOKIES.get('role')
    if role == 'ADMIN':
        return True
    return True

subscription_box/templates/box_detail.html
{% extends 'base.html' %}

{% block meta %}
<title>SubscriptionBox Detail</title>
{% endblock meta %}

{% block content %}
<p id="items" style="display: block;">{{ items }}</p>
<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-between align-items-center">
                <h1>{{ box.name }}</h1>
                <a class="btn btn-primary" href="{% url 'subscription_box:manager' %}">Back</a>
            </div>
        </div>
        <div class="card-body">
            <p>Price: {{ box.price }}</p>
            <p>Type: {{ box.type }}</p>
            <div class="container mt-4 flex justify-between">
                <div class="card mb-3">
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center">
                        <h2>Items</h2>
                        <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-2" id="create-item">Add Item</button>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table hover">
                            <thead>
                                <tr>
                                    <th>Item</th>
                                    <th>Quantity</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in items %}
                                <tr>
                                    <td>{{ item.name }}</td>
                                    <td>{{ item.quantity }}</td>
                                    <td>
                                        <a class="btn btn-outline-primary" href="{% url 'subscription_box:get_item' item.id %}">Detail</a>
                                        <button class="btn btn-outline-danger" onclick="deleteItem('{{item.id}}')" method="POST">Delete</button>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-1">Edit</button>
            <a class="btn btn-danger" onclick="deleteBox('{{id}}')">Delete</a>
        </div>
    </div>
</div>


<div class="modal fade" id="modal-1" tabindex="-1" aria-labelledby="modal-1-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-1-label">Edit</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" id="request-form-1">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ box.name }}">
                    </div>
                    <div class="mb-3">
                        <label for="price" class="form-label">Price</label>
                        <input type="number" class="form-control" id="price" name="price" value="{{ box.price }}" >
                    </div>
                    <div class="mb-3">
                        <label for="type" class="form-label">Type</label>
                        <input type="text" class="form-control" id="type" name="type" value="{{ box.type }}">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary" onclick="editBox('{{id}}')">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modal-2" tabindex="-1" aria-labelledby="modal-2-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-2-label">Create Item</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" id="request-form-2">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="itemName" name="name" required>
                    </div>
                    <div class="mb-3">
                        <label for="quantity" class="form-label">Quantity</label>
                        <input type="number" class="form-control" id="quantity" name="quantity" required>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary" onclick="createItem()">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    function deleteBox(boxId) {
        fetch(`/manage/box/delete/${boxId}`, {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            }
        })
        .then(response => {
            if (response.ok) {
                window.location.reload();
            } else {
                console.error('Error deleting box');
            }
        });
    }

    function editBox(boxId) {
        const response = fetch(`/manage/box/update/${boxId}`, {
            method: 'POST',
            body: new FormData(document.getElementById('request-form-1')),
        });

        if (response.ok) {
            window.location.reload();
        } else {
            console.error('Error editing box');
        }
    }

    function deleteItem(itemId) {
        console.log("deleteItem called with id:", itemId);
        const response = fetch(`/manage/item/delete/${itemId}`, {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            }
        })
        .then(response => {
            if (response.ok) {
                window.location.reload();
                refreshItem();
            }
        });
    }

    async function getItem(id) {
        const response = await fetch(`/manage/box/get/${id}`);
        const data = await response.json()
        const table = document.getElementById('boxesTable');
        const tbody = table.querySelector('tbody');
        tbody.innerHTML = '';
        data.items.forEach(item => {
             const tr = document.createElement('tr');
            tr.innerHTML = `
                <td>${item.name}</td>
                <td>${item.quantity}</td>
                <td>
                    <button class="btn btn-outline-primary" onclick="editItem(${item.id})">Detail</button>
                    <button class="btn btn-outline-danger" onclick="deleteItem('${item.id}')" method="POST">Delete</button>
                </td>
            `;
            tbody.appendChild(tr);
        });
    }

    function createItem() {
        fetch(`/manage/item/create`, {
            method: 'POST',
            body: new FormData(document.getElementById('request-form-2')),
        });
        updateIteminBox(url.substring(url.lastIndexOf('/') + 1));
        console.log("createItem called");
    }
    function updateIteminBox(boxId) {
        const response = fetch(`/manage/box/get/${id}`);
        const data = response.json();
        data.items.push({
            "name": document.getElementById('itemName').value,
            "quantity": document.getElementById('quantity').value,
        });
        fetch(`http://35.240.230.131/subscription-box/edit/${boxId}`, {
            method: 'PUT',
            body: JSON.stringify(data),
        });
        console.log("updateIteminBox called");
    }

    window.onload = async () => {
        const url = window.location.href;
        const id = url.substring(url.lastIndexOf('/') + 1);
        console.log("id:", id);
    }

</script>
{% endblock content %}

subscription_box/templates/item_detail.html
{% extends 'base.html' %}

{% block meta %}
<title>Item Detail</title>
{% endblock meta %}

{% block content %}
<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-between align-items-center">
                <h1>{{ item.name }}</h1>
                <a class="btn btn-primary" href="{% url 'subscription_box:manager' %}">Back</a>
            </div>
        </div>
        <div class="card-body">
            <p>Quantity: {{ item.quantity }}</p>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-1">Edit</button>
            <a class="btn btn-danger" onclick="deleteItem('{{id}}')">Delete</a>
        </div>
    </div>
</div>


<div class="modal fade" id="modal-1" tabindex="-1" aria-labelledby="modal-1-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-1-label">Edit</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" id="request-form-1">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ item.name }}">
                    </div>
                    <div class="mb-3">
                        <label for="quantity" class="form-label">Quantity</label>
                        <input type="number" class="form-control" id="quantity" name="quantity" value="{{ item.quantity }}" >
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary" onclick="editItem('{{id}}')">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    function deleteItem(itemId) {
        fetch(`/manage/item/delete/${itemId}`, {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            }
        })
        .then(response => {
            if (response.ok) {
                window.location.reload();
            } else {
                console.error('Error deleting item');
            }
        });
    }

    function editItem(itemId) {
        const response = fetch(`/manage/item/update/${itemId}`, {
            method: 'POST',
            body: new FormData(document.getElementById('request-form-1')),
        });

        if (response.ok) {
            window.location.reload();
        } else {
            console.error('Error editing item');
        }
    }

    async function get_item(id) {
        const response = await fetch(`/manage/item/get/${id}`);
        const data = await response.json();
        return data;
    }

    window.onload = async () => {
        const url = window.location.href;
        const id = url.split('/').pop();
        const item = await get_item(id);
        document.getElementById('name').value = item.name;
        document.getElementById('quantity').value = item.quantity;
    }

</script>
{% endblock content %}

subscription_box/templates/manager.html
{% extends 'base.html' %}

{% block meta %}
<title>Subscription Box Manager</title>
{% endblock meta %}

{% block content %}
<div class="modal fade" id="modal-1" tabindex="-1" aria-labelledby="modal-1-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-1-label">Create a Subscription Box</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" id="request-form-1">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                    <div class="mb-3">
                        <label for="price" class="form-label">Price</label>
                        <input type="number" class="form-control" id="price" name="price" required>
                    </div>
                    <div class="mb-3">
                        <label for="type" class="form-label">Type</label>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="type" id="qtr" value="QTR">
                            <label class="form-check-label" for="qtr">QTR</label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="type" id="mth" value="MTH">
                            <label class="form-check-label" for="mth">MTH</label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="type" id="saa" value="SAA">
                            <label class="form-check-label" for="saa">SAA</label>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary" onclick="createSubscription()">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-2" tabindex="-1" aria-labelledby="modal-2-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-2-label">Create Item</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" id="request-form-2">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                    <div class="mb-3">
                        <label for="quantity" class="form-label">Quantity</label>
                        <input type="number" class="form-control" id="quantity" name="quantity" required>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary" onclick="createItem()">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<h1>Subscription Box Manager</h1>
<div class="container mt-4 flex justify-between">
    <div class="card mb-3">
        <div class="card-header">
            <div class="d-flex justify-content-between align-items-center">
                <h2>Subscription Boxes</h2>
                <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-1" id="create-box">Add Subscription Box</button>
            </div>
        </div>
        <div class="card-body">
            <table class="table hover" id="boxesTable">
                <thead>
                    <tr>
                        <th>Subscription Box</th>
                        <th>Price</th>
                        <th>Type</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for box in boxes %}
                    <tr>
                        <td>{{ box.name }}</td>
                        <td>{{ box.price }}</td>
                        <td>{{ box.type }}</td>
                        <td>
                            <a class="btn btn-outline-primary" href="{% url 'subscription_box:get_subscription' box.id %}">Detail</a>
                            <button class="btn btn-outline-danger"  onclick="deleteBox('{{box.id}}')" method="POST">Delete</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="container mt-4 flex justify-between">
    <div class="card mb-3">
        <div class="card-header">
            <div class="d-flex justify-content-between align-items-center">
            <h2>Items</h2>
            <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-2" id="create-item">Add Item</button>
            </div>
        </div>
        <div class="card-body">
            <table class="table hover">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Quantity</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>
                            <a class="btn btn-outline-primary" href="{% url 'subscription_box:get_item' item.id %}">Detail</a>
                            <button class="btn btn-outline-danger" onclick="deleteItem('{{item.id}}')" method="POST">Delete</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>




<script>
    function deleteItem(itemId) {
        console.log("deleteItem called with id:", itemId);
        const response = fetch(`/manage/item/delete/${itemId}`, {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            }
        })
        .then(response => {
            if (response.ok) {
                window.location.reload();
                refreshItem();
            }
        });
    }

    function deleteBox(boxId) {
        console.log("deleteBox called with id:", boxId);
        const response = fetch(`/manage/box/delete/${boxId}`, {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            }
        })
        .then(response => {
            if (response.ok) {
                window.location.reload();
                refreshBox();
            }
        });
    }

    async function refreshBox() {
        const response = await fetch('{% url "subscription_box:all_subscriptions" %}' );
        const data = await response.json();
        console.log(data);
        const table = document.getElementById('boxesTable');
        const tbody = table.querySelector('tbody');
        tbody.innerHTML = '';
        data.forEach(box => {
            const tr = document.createElement('tr');
            tr.innerHTML = `
                <td>${box.name}</td>
                <td>${box.price}</td>
                <td>${box.type}</td>
                <td>
                    <button class="btn btn-outline-primary" onclick="getBox(${box.id})">Detail</button>
                    <button class="btn btn-outline-danger" onclick="deleteBox('${box.id}')" method="POST">Delete</button>
                </td>
            `;
            tbody.appendChild(tr);
        });
    }

    async function refreshItem() {
        const response = await fetch('{% url "subscription_box:all_items" %}');
        const data = await response.json();
        const table = document.getElementById('itemsTable');
        const tbody = table.querySelector('tbody');
        tbody.innerHTML = '';
        data.forEach(item => {
            const tr = document.createElement('tr');
            tr.innerHTML = `
                <td>${item.name}</td>
                <td>${item.quantity}</td>
                <td>
                    <button class="btn btn-outline-primary" onclick="getItem(${item.id})">Detail</button>
                    <button class="btn btn-outline-danger" onclick="deleteItem('${item.id}')" method="POST">Delete</button>
                </td>
            `;
            tbody.appendChild(tr);
        });
    }

    function createSubscription() {
        const form = document.getElementById('request-form-1');
        fetch('/manage/box/create', {
            method: "POST",
            body: new FormData(form)
        })
        .then((response) => {
            if (response.ok) {
                window.location.reload();
                refreshBox();   
            }
        });  
    }

    function createItem() {
        const form = document.getElementById('request-form-2');
        const formData = new FormData(form);
        fetch('/manage/item/create', {
            method: 'POST',
            body: formData
        }).then(response => {
            if (response.ok) {
                window.location.reload();
                refreshItem();
            }
        });
    }

    window.onload = async function(){
        refreshBox();
        refreshItem();
    }
</script>
{% endblock content %}