authentication/urls.py
from django.urls import path
from authentication.views import register, login, logout_user, profile_delete, profile_detail, profile_edit

app_name = 'authentication'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login, name='login'),
    path('logout/', logout_user, name='logout_user'),
    path('profiles/<str:username>/', profile_detail, name='profile_detail'),
    path('profiles/<str:username>/edit/', profile_edit, name='profile_edit'),
    path('profiles/<str:username>/delete/', profile_delete, name='profile_delete'),
]

frontend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('manage/', include('subscription_box.urls')),
    path('subscription/', include('subscription_management.urls')), 
    path('auth/', include('authentication.urls')),
    path('reviews/', include('subsbox_review.urls'))
]

homepage/urls.py
from django.urls import path
from homepage.views import show_homepage
app_name = 'homepage'

urlpatterns = [
    path('', show_homepage, name='show_homepage'),
]

subscription_box/subscription_box/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    
]

homepage/views.py
from django.shortcuts import render

def show_homepage(request):
    context = {
        'username': request.COOKIES.get('username')
    }
    return render(request, "homepage.html", context)

homepage/templates/homepage.html
{% extends 'base.html' %}

{% block meta %}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta name="description" content="" />
<meta name="author" content="" />
<title>B12 - Subscription Boxes</title>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
{% endblock meta %}

{% block content %}
<header class="bg-light py-5">
    <div class="container text-center">
        <h1 class="display-4 font-weight-bold">Subscription Boxes - B12</h1>
        <div class="my-4">
            <a href="{% url 'authentication:login' %}" class="btn btn-primary btn-lg mx-2">Login</a>
            <a href="{% url 'authentication:register' %}" class="btn btn-primary btn-lg mx-2">Register</a>
        </div>
    </div>
</header>
{% endblock content %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}